yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"

npmScopes:
  tryvium-pay:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN:-}

