nodeLinker: node-modules

npmScopes:
  tryvium-pay:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
