yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
npmPublishRegistry: "https://npm.pkg.github.com"
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: PUT_YOUR_TOKEN

npmScopes:
  tryvium-pay:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: PUT_YOUR_TOKEN